apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-tkjsizps
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-tkjsizps:10a9d4f3e3e52f003499ba9c05bcec103b902e0f@sha256:f096b15c72f70647a000b566f957a79bcece622d648ee43f5906d9c1553c0ffa
          name: container-image
